#ifndef COMMANDS_H
#define COMMANDS_H

#define CMD_TRIGGER_FORCE ":TRIGger:FORCe"
#define CMD_ID_QUERY "*IDN?"
#define CMD_CHANNEL1_OFF ":SELECT:CH1 OFF"
#define CMD_CHANNEL1_ON ":SELECT:CH1 ON"
#define CMD_CHANNEL2_OFF ":SELECT:CH2 OFF"
#define CMD_CHANNEL2_ON ":SELECT:CH2 ON"
#define CMD_CHANNEL3_OFF ":SELECT:CH3 OFF"
#define CMD_CHANNEL3_ON ":SELECT:CH3 ON"
#define CMD_CHANNEL4_OFF ":SELECT:CH4 OFF"
#define CMD_CHANNEL4_ON ":SELECT:CH4 ON"
#define CMD_CHANNEL5_OFF ":SELECT:CH5 OFF"
#define CMD_CHANNEL5_ON ":SELECT:CH5 ON"
#define CMD_CHANNEL6_OFF ":SELECT:CH6 OFF"
#define CMD_CHANNEL6_ON ":SELECT:CH6 ON"
#define CMD_CHANNEL7_OFF ":SELECT:CH7 OFF"
#define CMD_CHANNEL7_ON ":SELECT:CH7 ON"
#define CMD_CHANNEL8_OFF ":SELECT:CH8 OFF"
#define CMD_CHANNEL8_ON ":SELECT:CH8 ON"
// Add more as needed

#endif